apiVersion: apps/v1
kind: Deployment
metadata:
  name: assetservice-deployment
  labels:
    app: assetservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assetservice
  template:
    metadata:
      labels:
        app: assetservice
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
      - image: assetservice:latest
        imagePullPolicy: Never
        name: assetservice
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "60Mi"
            cpu: "250m"
          limits:
            memory: "100Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: assetservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: assetservice
  ports:
    - port: 8080