networks:
    appnetwork:
        name: appnetwork
        driver: bridge

volumes:
    app-db-data:
            
services:
    gatewayservice:
        image: gatewayservice
        build:
            context: .
            dockerfile: ./SandAndStones.Gateway.Api/Dockerfile
        ports: 
           - "5000:5000"
        networks:
            - appnetwork
    
    assetinfoservice:
        image: assetservice
        build: 
            context: .
            dockerfile: ./SandAndStones.Api/Dockerfile
        environment:
            DbServer: "mssql-server"
            DbPort: "1433"
            DbUser: "sa"
            DbPass: "Docker1234!"
            DbName: "SandAndStones.Database"
        ports: 
           - "42000:8080"
        depends_on:
           - mssql-server
        networks:
            - appnetwork
    
    mssql-server:
        container_name: sqldb
        image: mcr.microsoft.com/mssql/server:latest
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=Docker1234!
          - MSSQL_PID=Express
        volumes:
        - type: volume
          source: app-db-data
          target: /var/opt/mssql
        ports:
          - 5433:1433
        networks:
            - appnetwork