networks:
    appnetwork:
        name: appnetwork
        driver: host

volumes:
    app-db-data:
    mongo-db-data:
         
secrets:
  DEVPASS:
    environment: "DEVPASS"

services:
    clientapp:
        build:
            context: .
            dockerfile: SandAndStones.ClientApp/Dockerfile
        ports:
            - "8080:8080"
        networks:
            - appnetwork
        volumes:
            - ./SandAndStones.ClientApp:/app
            - /app/node_modules
            - ./SandAndStones.ClientApp/cert.pem:/app/cert.pem:ro
            - ./SandAndStones.ClientApp/key.pem:/app/key.pem:ro
        environment:
            NODE_ENV: production
        stdin_open: true
        tty: true
        env_file:
            - .env


    gatewayservice:
        image: gatewayservice
        build:
            context: .
            dockerfile: ./SandAndStones.Gateway.Api/Dockerfile
            secrets:
              - DEVPASS
        environment:
            ASPNETCORE_ENVIRONMENT: Local
            ASPNETCORE_URLS: https://+:5000;http://+:5098
            ASPNETCORE_HTTP_PORTS: 5098 
            ASPNETCORE_HTTPS_PORTS: 5000
            ASPNETCORE_Kestrel__Certificates__Default__Password: ${DEVPASS}
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
        ports: 
           - "5000:5000"
           - "5098:5098"
        depends_on:
           - mssql-server
        networks:
            - appnetwork
        volumes:
        - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    
    assetservice:
        image: assetservice
        build: 
            context: .
            dockerfile: ./SandAndStones.Asset.Api/Dockerfile
            secrets:
              - DEVPASS
        environment:
            ASPNETCORE_ENVIRONMENT: Local
            ASPNETCORE_URLS: https://+:7232;http://+:5295
            ASPNETCORE_HTTP_PORTS: 5295
            ASPNETCORE_HTTPS_PORTS: 7232
            ASPNETCORE_Kestrel__Certificates__Default__Password: ${DEVPASS}
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
        ports: 
           - "7232:7232"
           - "5295:5295"
        depends_on:
           - mssql-server
        networks:
            - appnetwork
        volumes:
        - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    
    textureservice:
        image: textureservice
        build: 
            context: .
            dockerfile: ./SandAndStones.Texture.Api/Dockerfile
            secrets:
              - DEVPASS
        environment:
            ASPNETCORE_ENVIRONMENT: Local
            ASPNETCORE_URLS: https://+:7077;http://+:5018
            ASPNETCORE_HTTP_PORTS: 5018
            ASPNETCORE_HTTPS_PORTS: 7077
            ASPNETCORE_Kestrel__Certificates__Default__Password: ${DEVPASS}
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
        ports: 
           - "7077:7077"
           - "5018:5018"
        depends_on:
           - mssql-server
           - texture-blob-storage
        networks:
            - appnetwork
        volumes:
        - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    
    eventlogservice:
        image: eventlogservice
        build: 
            context: .
            dockerfile: ./SandAndStones.EventLog.Api/Dockerfile
            secrets:
              - DEVPASS
        environment:
            ASPNETCORE_ENVIRONMENT: Local
            ASPNETCORE_URLS: https://+:7004;http://+:5215
            ASPNETCORE_HTTP_PORTS: 5215
            ASPNETCORE_HTTPS_PORTS: 7004
            ASPNETCORE_Kestrel__Certificates__Default__Password: ${DEVPASS}
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
        ports: 
           - "7004:7004"
           - "5215:5215"
        depends_on:
          - mongodb
        networks:
            - appnetwork
        volumes:
        - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    
    mssql-server:
        container_name: sqldb
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: ${DEVPASS}
          MSSQL_PID: Developer
        secrets:
          - DEVPASS
        volumes:
        - type: volume
          source: app-db-data
          target: /var/opt/mssql
        ports:
          - 5433:1433
        networks:
            - appnetwork

    texture-blob-storage:
      image: mcr.microsoft.com/azure-storage/azurite:latest
      container_name: sandandstones-texture.blob-storage
      volumes:
      - ./.container/blob_storage/data:/data
      ports:
      - "20000:10000"
      command: "azurite-blob -- --blobhost 0.0.0.0:20000 -l /data"

    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
          - mongo-db-data:/data/db
        ports:
          - 27017:27017
        networks:
            - appnetwork