services: 
    assetinfoservice:
        image: inputassetbatchservice
        build: 
            context: .
            dockerfile: ./inputassetbatchservice/Dockerfile
        ports: 
           - "42000:8080"