# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - sand-and-stones-frontend-app-0001

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-frontend-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        working-directory: ./SandAndStones.ClientApp
        run: | 
          npm ci
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./SandAndStones.ClientApp/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy-frontend-app:
    runs-on: ubuntu-latest
    needs: build-frontend-app
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-frontend-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-frontend-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sand-and-stones-frontend-app-0001'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5675EFAD7A5C44CE96D49B5B774868F4 }}
