name: build-and-deploy
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build --configuration Debug

      - name: dotnet publish
        run: dotnet publish -c Debug -o ${{env.DOTNET_ROOT}}/myapp

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: npm install, build
        working-directory: ./SandAndStones.ClientApp
        run: | 
          npm ci
          npm run build --if-present
