name: microservices-deployment
on:
  push: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.checkoutRef }}
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore ./SandAndStonesEngineMicroservices.sln
      - name: Build
        run: dotnet build ./SandAndStonesEngineMicroservices.sln --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./SandAndStonesEngineMicroservices.sln --configuration Release --no-build -o ${{env.DOTNET_ROOT}}/app
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: app-artifact
          path: ${{env.DOTNET_ROOT}}/app
          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: PROD
      url: ${{steps.deploy-to-azure.outputs.webapp-url}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with: 
          name: app-artifact
      - name: Azure WebApp Deploy
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v3.0.1
        with: 
         app-name: 'sand-and-stones-microservices0001'
         publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
         
